---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks:
  - name: 01. Create a VM folder on given datacenter
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      folder_name: '{{ project_id }}'
      parent_folder: "4.Projects"
      folder_type: vm
      state: present
      validate_certs: false
    register: vm_folder_creation_result
    delegate_to: localhost
