---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks: 
  - name: 03. Adding Private Openshift Portgroup
    community.vmware.vmware_portgroup:
      hostname: '{{ esxi_hostname }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      switch: '{{ project_id }}'
      hosts:  '{{ esxi_hostname }}'
      portgroup: "{{ project_id + '-Openshift'}}"
      validate_certs: false
      security:
          promiscuous_mode: True
          mac_changes: True
          forged_transmits: True
    delegate_to: localhost