---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks:
  - name: 02. Create Project Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ esxi_hostname }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      switch: '{{ project_id }}'
      validate_certs: no
    delegate_to: localhost

  